sudo: required
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.22.0
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
script:
  # Build & test backend
  - docker pull cfranklin11/tipresias_server:master
  - docker build --cache-from cfranklin11/tipresias_server:master -t cfranklin11/tipresias_server:master ./backend
  - docker run cfranklin11/tipresias_server:master pylint --disable=R server project scripts
  - docker run cfranklin11/tipresias_server:master mypy server project scripts
  - docker-compose -f docker-compose.ci.yml run backend python3 -Wi manage.py test
  # Build & test frontend
  - docker pull cfranklin11/tipresias_client:master
  - docker build --cache-from cfranklin11/tipresias_client:master -t cfranklin11/tipresias_client:master ./frontend
  - docker run cfranklin11/tipresias_client:master yarn run eslint src
  - docker run cfranklin11/tipresias_client:master yarn run flow
  - docker run -e CI=true cfranklin11/tipresias_client:master yarn run test:unit
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u cfranklin11 --password-stdin
  - docker push cfranklin11/tipresias_server:master
  - docker push cfranklin11/tipresias_client:master
deploy:
  provider: heroku
  api_key:
    secure: DNFbg9pkA4RZe/nUffDo+fOFa3c+OVbecO08HgYcW93T0IEqW4R4jdGO4xpZof/7066Ue7RdsGHSrr7TKZnLImgcqtblNv0/H/MTLorEXJ/Kmeg3RBGvyT67aM2ZhCUIh9hZij+irmzT5/uXdHGsH/GyoPUtaTRyaEziqlLtkM7Muq9NExcPIuh2sVWQhCQmRRNNtKtSdoWu0OpwrSSTE8jeBE9coi+YgncqqqzrqTbbd+uxxgSWVTl7bbjj9yR7v/UFEWS+BVOXTDA4u8LlQFOvHi93mi4r228UxtUkcUfyKeUZlVhQLAkj5YnRqrjYQWB/QiRbvbEbCf248kI68IdNv4/jgYdEzMS0K9Imf2iKoo+joQOFMfXTUHXqHv/SyNq6l4jJeinYk5tLJUOKaw2MdKy73uTdzX/jMgMJ8f5zRen+BSskLx23jOwxK/qmdjBnGB/EPrT0TAARrCo6aFL0VTZslSQtDqqvyVwaYCy+PtVwrdeCZP0iJbnBSZpDofr8oq882UJGQj7NPrVJ7HBTAFD8posJIPln8F4CKOVUjF0FkOKIuvimpmJF84ziJdf4cgi2hWsXlJyJTiBpRRnEsnHlfeRsZHyt6nhbkc3ARwdr5Nh0GJkJBVmRq04LjA8oY5kMlSmoCAdUHrnfYj+b9VmlrrmxPs6bkSbWJNk=
  app: tipresias
  on: master
