sudo: required
services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.22.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - docker pull cfranklin11/tipresias_server:master
  - docker build --cache-from cfranklin11/tipresias_server:master -t cfranklin11/tipresias_server:master ./backend
  - docker run cfranklin11/tipresias_server:master pylint --disable=R server project scripts
  - docker-compose -f docker-compose.ci.yml run backend python3 -Wi manage.py test
  
  - docker pull cfranklin11/tipresias_client:master
  - docker build --cache-from cfranklin11/tipresias_client:master -t cfranklin11/tipresias_client:master ./frontend
  - docker run cfranklin11/tipresias_client:master yarn run eslint src
  - docker run cfranklin11/tipresias_client:master yarn run flow
  - docker run -e CI=true cfranklin11/tipresias_client:master yarn run test:unit

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u cfranklin11 --password-stdin
  - docker push cfranklin11/tipresias_server:master
  - docker push cfranklin11/tipresias_client:master

deploy:
  provider: heroku
  api_key:
    secure: Nyr9M/g2o3uZ9HGQ+c7OHMTcTMj6f2MY6uS3xiwvDObzen+p42TaQ74MTKFPbJYbHX3fHjVxEjeLlsojeAF9w6w5JbVO/0937snXynky/NXzD1ZU7JNq+xvjwBFjuSouuw/bT+YH0gnI0euZcofGNYijpIwoLg61b2McTISbKswQZmTmqXCBCfPa2YUp7A9+L+0Cr2hEPNbb5sVaMIgMjU7O1aplFfSweHC9LtiRl3t8nbOx7t/vO2/NBZxHqFirDqd2m/PfrbNDdXM0kAvOSshT2JSrQj7OHFnLwVlX6OrUjCRPhwOhRERDaryg7wBK+voVcqfQD/JwFzUJ6O+pkFe1yqcTi8c/lyriwnaEaTmhTOoRPd1pydpl0n1DQWAktscGVQ8QXr0yq9S1UIBGDdNrqrN4e4VDEBVahI8WyA6Gw2o7c6tYKySszKUCzITwmcjVn0SHJme2LIHKZRihIjmpj8LXzUbd5uFW1fvDDTilZugUrdltjAMFphjUca1vCC1iAcYozg+mzNFXkfRlMKCuUiW1nSfV4yRttKIEaWjKWSQ9g8otgz7Fz943/dvZflhS2sD4PlKxN5RBLRcx6CA7SuMJWoVT1X9CDXylpFELPMtSluDUfrtZ5nn6XY0eI8zEIW9f+N6owbqP93Mb3qjdau3zm5tnYFLkEy1dO00=
  app: tipresias
  on: master
