version: "3.1"
services:
  server:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - server
    command: yarn start
  notebook:
    image: tipresias_server:latest
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
